---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    # - name: Test running the CsSensorSettings command
    #   ansible.windows.win_command: '"C:\Program Files\CrowdStrike\CsSensorSettings" --version'

    - name: Run Migrate Script
      ansible.builtin.script: >
        ../../powershell/migrate/migrate_single.ps1
        -NewFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -NewFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -OldFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}" `
        -OldFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -NewFalconCloud "us-2"
        -OldFalconCloud "us-2"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
        -RemoveHost
        -Tags "migrate1,migrate2"
        -FalconTags "tag1,tag2"
