---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Run Migrate Script
      ansible.builtin.script: >
        ../../powershell/migrate/falcon_windows_migrate.ps1
        -NewFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -NewFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -OldFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}" `
        -OldFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -NewFalconCloud "{{ lookup('env', 'FALCON_CLOUD') }}"
        -OldFalconCloud "{{ lookup('env', 'FALCON_CLOUD') }}"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
        -RemoveHost
        -Tags "migrate1,migrate2"
        -FalconTags "tag1,tag2"
    #   register: install_script

    # # Print stdout
    # - name: Task STDOUT
    #   ansible.builtin.debug:
    #     msg: "{{ install_script.stdout_lines }}"
