---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Run Migrate Script
      ansible.windows.win_shell: >
        {{ remote_script_dest }}\migrate.ps1
        -NewFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -NewFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -OldFalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}" `
        -OldFalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -NewFalconCloud "us-2"
        -OldFalconCloud "us-2"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
        -Tags "molecule"
        -FalconTags "molecule"
      args:
        chdir: "{{ remote_script_dest }}"
