---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: falcon
    box: "jborean93/${MOLECULE_DISTRO:-WindowsServer2019}"
    box_version: 1.0.0
    memory: 8192
    cpus: 3
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  inventory:
    host_vars:
      falcon:
        ansible_become: False
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 55986
        remote_script_dest: C:\Temp\migrate
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
