---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Run Install Script
      ansible.builtin.script: >
        ../../powershell/install/falcon_windows_install.ps1
        -FalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -FalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
        -Tags "existing1,existing2"
