---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Create Remote Script Directory
      ansible.windows.win_file:
        path: "{{ remote_script_dest }}"
        state: directory

    - name: Copy Install Scripts
      ansible.windows.win_copy:
        src: "{{ item }}"
        dest: "{{ remote_script_dest }}\\"
      loop:
        - ../../powershell/install/falcon_windows_install.ps1
        - ../../powershell/install/falcon_windows_uninstall.ps1
        - ../../powershell/migrate/migrate.ps1

    - name: Run Install Script
      ansible.windows.win_shell: >
        {{ remote_script_dest }}\falcon_windows_install.ps1
        -FalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -FalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
        -Tags "falcon,install"
      args:
        chdir: "{{ remote_script_dest }}"
