---
- name: Verify
  hosts: all
  tasks:
    - name: Check status of Falcon Sensor
      ansible.windows.win_command: sc.exe query csagent
      register: win_status

    - name: Verify Falcon Sensor is installed and running
      ansible.builtin.assert:
        that: "'RUNNING' in win_status.stdout"

# TODO: Create task to verify Tags
# Sensor Tags should be: falcon,install,molecule
# Grouping Tags should be: FalconGroupingTags/molecule
