---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Run Install Script w/ CID
      ansible.builtin.script: >
        ../../powershell/install/falcon_windows_install.ps1
        -FalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        -FalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        -FalconCid "{{ lookup('env', 'FALCON_CID') }}"
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"
    #   register: install_script

    # # Print stdout
    # - name: Task STDOUT
    #   ansible.builtin.debug:
    #     msg: "{{ install_script.stdout_lines }}"
