---
- name: Converge
  hosts: all
  tasks:
    - name: Run Powershell Script
      ansible.builtin.script: |
        ../../powershell/install/falcon_windows_install.ps1 `
        -FalconClientId "{{ lookup('env', 'FALCON_CLIENT_ID') }}" `
        -FalconClientSecret "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}" `
        -ProvToken "{{ lookup('env', 'FALCON_PROV_TOKEN') }}"