---
# Run default verify playbook
- name: Verify (Default)
  ansible.builtin.import_playbook: ../bash_install/verify.yml

- name: Verify (Get Current Sensor Version)
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Set current sensor version
      ansible.builtin.set_fact:
        current_sensor_version: "{{ ansible_facts.packages[installed_sensor][0].version }}"

    # Uninstall, then reinstall the sensor using latest
    - name: Stop the sensor (deb hack)
      ansible.builtin.service:
        name: falcon-sensor
        state: stopped
      when: ansible_facts.pkg_mgr == "apt"

    - name: Uninstall Falcon Sensor
      ansible.builtin.package:
        name: "{{ installed_sensor }}"
        state: absent

# Run converge.yml to install the latest version of the sensor
- name: Verify (Install Latest Sensor)
  ansible.builtin.import_playbook: ../bash_install/converge.yml

- name: Verify (Compare Sensor Versions)
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Get list of installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify Falcon Sensor is installed
      ansible.builtin.assert:
        that: installed_sensor in ansible_facts.packages

    - name: Set latest sensor version
      ansible.builtin.set_fact:
        latest_sensor_version: "{{ ansible_facts.packages[installed_sensor][0].version }}"

    - name: Verify current sensor version is not equal to latest sensor version
      ansible.builtin.assert:
        that: current_sensor_version != latest_sensor_version
