---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Get list of installed packages
    ansible.builtin.package_facts:
      manager: auto

  - name: Set default sensor name
    ansible.builtin.set_fact:
      installed_sensor: falcon-sensor

  - name: Verify Falcon Sensor is installed
    ansible.builtin.assert:
      that: installed_sensor in ansible_facts.packages

  - name: Collect status of falcon-sensor service
    ansible.builtin.service_facts:

  - name: Verify falcon-sensor service is not active
    ansible.builtin.assert:
      that: ansible_facts.services[installed_sensor + '.service'].state == 'stopped'
