name: "CI: bash_install"
on:
  schedule:
    - cron: '0 0 * * *'

  push:
    paths:
      - 'molecule/bash_install/**'
      - 'bash/install/**'
      - '.github/workflows/bash_install.yml'

  pull_request:
    paths:
      - 'molecule/bash_install/**'
      - 'bash/install/**'
      - '.github/workflows/bash_install.yml'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Shellcheck
        run: |
          shellcheck --version
          shellcheck bash/install/falcon-linux-install.sh

  molecule-test:
    name: Molecule Test
    permissions:
      contents: read
      id-token: write
    needs: validate
    uses: ./.github/workflows/reusable-molecule-test-linux.yml
    with:
      distros: |
        [
          {"name": "ubuntu-20.04", "image_owner": "099720109477", "image_arch": "x86_64", "image_name": "ubuntu/images/hvm-ssd/ubuntu-focal-20.04*", "instance_type": "t2.micro"},
          {"name": "ubuntu-22.04", "image_owner": "099720109477", "image_arch": "x86_64", "image_name": "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04*", "instance_type": "t2.micro"},
          {"name": "amazon-2023", "image_owner": "137112412989", "image_arch": "x86_64", "image_name": "al2023-ami-2023*", "instance_type": "t2.micro"},
          {"name": "amazon-2", "image_owner": "137112412989", "image_arch": "x86_64", "image_name": "amzn2-ami-hvm-2.0*gp2", "instance_type": "t2.micro"},
          {"name": "sles-15-sp5", "image_owner": "013907871322", "image_arch": "x86_64", "image_name": "suse-sles-15-sp5-v????????-hvm*", "instance_type": "t2.micro"},
          {"name": "almalinux-8", "image_owner": "679593333241", "image_arch": "x86_64", "image_name": "AlmaLinux OS 8*", "instance_type": "t2.micro"},
          {"name": "rhel-9", "image_owner": "309956199498", "image_arch": "x86_64", "image_name": "RHEL-9.?.?_HVM-*", "instance_type": "t2.micro"},
          {"name": "rhel-9-arm", "image_owner": "309956199498", "image_arch": "arm64", "image_name": "RHEL-9.?.?_HVM-*", "instance_type": "t4g.micro"}
        ]
      collection_role: bash_install
      pr_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      pr_repo: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || '' }}
    secrets: inherit
