name: "Integration Tests: Windows"
on:
  schedule:
    - cron: '0 6 * * *'

  push:
    paths:
      - 'molecule/pwsh**'
      - 'powershell/install/**'
      - '.github/workflows/ci-windows.yml'

  pull_request_target:
    types: [ labeled ]
    paths:
      - 'molecule/pwsh**'
      - 'powershell/install/**'
      - '.github/workflows/ci-windows.yml'
jobs:
  molecule:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request_target' &&
      github.event.label.name == 'ok-to-test')
    runs-on: macos-12
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
      FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
      FALCON_CID: ${{ secrets.FALCON_CID }}
      FALCON_PROV_TOKEN: ${{ secrets.FALCON_PROV_TOKEN }}
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          - { "distro":"WindowsServer2019" }
        scenario:
          - pwsh_install_policy
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request_target'

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
        if: github.event_name == 'pull_request_target'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '.github/workflows/ci-windows.yml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[lint] ansible yamllint ansible-lint python-vagrant molecule-vagrant "pywinrm>=0.3.0"
      
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('./molecule/pwsh_install_policy/molecule.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Run integration tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          retry_on: error
          command: >-
            molecule --version &&
            ansible --version &&
            MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
            molecule test -s ${{ matrix.scenario }}