---
name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.github/mlc_config.json'
          base-branch: main
