---
name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@4a1af151f4d7cf4d8f8ac5780597672a3671b88b # 1.0.17
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.github/mlc_config.json'
          base-branch: main
