name: PSScriptAnalyzer

on:
  push:
    paths:
      - 'powershell/**'
      - '.github/workflows/psscriptanalyzer.yml'

  pull_request:
    paths:
      - 'powershell/**'
      - '.github/workflows/psscriptanalyzer.yml'

permissions:
  contents: read
  security-events: write

jobs:
  powershell:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f # v1.1
        with:
          path: .\powershell
          recurse: true
          excludeRule: '"PSUseShouldProcessForStateChangingFunctions"'
          output: 'results.sarif'
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@fbcef3fba75224ed6476919775448de80b23cb15 # v3.32.0
        with:
          sarif_file: results.sarif
