name: Shell Format Check

on:
  pull_request:
    paths:
      - 'bash/**'
      - '.github/workflows/shell_format.yml'

permissions:
  contents: read

jobs:
  shfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Run shfmt with reviewdog
      uses: reviewdog/action-shfmt@d8f080930b9be5847b4f97e9f4122b81a82aaeac # v1.0.4
      with:
        fail_on_error: true
        workdir: 'bash'
        shfmt_flags: '-i 4 -ci'


