name: Shell Format Check

on:
  pull_request:
    paths:
      - 'bash/**'
      - '.github/workflows/shell_format.yml'

permissions:
  contents: read

jobs:
  shfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run shfmt with reviewdog
      uses: reviewdog/action-shfmt@650566520dd8dfd3ac8f4129754a0aa342fdda4d # v1.0.4
      with:
        fail_on_error: true
        workdir: 'bash'
        shfmt_flags: '-i 4 -ci'


