name: ShellCheck Linting

on:
  push:
    paths:
      - 'bash/**'
      - '.github/workflows/shellcheck.yml'

  pull_request:
    paths:
      - 'bash/**'
      - '.github/workflows/shellcheck.yml'

permissions:
  contents: read

jobs:
  bash:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      with:
        format: tty
        scandir: './bash'

  dash:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Run ShellCheck to check against dash shells
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      with:
        format: tty
        scandir: './bash'
      env:
        SHELLCHECK_OPTS: --shell dash
